# Generated by Django 4.1 on 2022-10-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_message_body_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
