# Generated by Django 4.1 on 2022-10-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
